import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../../services/firestore_service.dart';
import '../../models/expense_model.dart';
import '../../theme.dart';
import 'add_expense_screen.dart';

class ExpensesScreen extends StatelessWidget {
  const ExpensesScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final svc = FirestoreService();
    final cf = NumberFormat.currency(locale: 'en_IN', symbol: '₹');
    final df = DateFormat('dd MMM');

    return Scaffold(
      appBar: AppBar(title: const Text('Expenses')),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () => Navigator.push(context,
            MaterialPageRoute(builder: (_) => const AddExpenseScreen())),
        icon: const Icon(Icons.add),
        label: const Text('Add Expense'),
        backgroundColor: AppTheme.primary,
        foregroundColor: Colors.white,
      ),
      body: StreamBuilder<List<ExpenseModel>>(
        stream: svc.streamExpenses(),
        builder: (ctx, snap) {
          if (snap.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          final expenses = snap.data ?? [];
          if (expenses.isEmpty) {
            return Center(
              child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
                Icon(Icons.receipt_outlined, size: 64, color: Colors.grey.shade300),
                const SizedBox(height: 16),
                const Text('No expenses recorded.'),
              ]),
            );
          }

          // Category totals (exclude COGS from the cash summary)
          final byCategory = <String, double>{};
          double cashTotal = 0;
          double cogsTotal = 0;
          for (final e in expenses) {
            byCategory[e.category] = (byCategory[e.category] ?? 0) + e.amount;
            if (e.isCogs) {
              cogsTotal += e.amount;
            } else {
              cashTotal += e.amount;
            }
          }

          return Column(children: [
            // Summary chips
            Container(
              height: 64,
              padding: const EdgeInsets.symmetric(horizontal: 12),
              child: ListView(
                scrollDirection: Axis.horizontal,
                children: [
                  _CategoryChip('Cash Total', cf.format(cashTotal), Colors.grey.shade700),
                  if (cogsTotal > 0)
                    _CategoryChip('Materials (COGS)', cf.format(cogsTotal),
                        Colors.brown.shade400),
                  ...byCategory.entries
                      .where((e) => e.key != 'Raw Materials (COGS)')
                      .map((e) => _CategoryChip(e.key, cf.format(e.value), AppTheme.payable)),
                ],
              ),
            ),
            Expanded(
              child: ListView.builder(
                padding: const EdgeInsets.fromLTRB(12, 0, 12, 80),
                itemCount: expenses.length,
                itemBuilder: (ctx, i) {
                  final e = expenses[i];
                  final isCogs = e.isCogs;
                  final isAuto = e.isAutoGenerated;
                  final avatarColor = isCogs
                      ? Colors.brown.shade400
                      : AppTheme.payable;

                  return Card(
                    margin: const EdgeInsets.only(bottom: 6),
                    color: isCogs ? Colors.brown.shade50 : null,
                    child: ListTile(
                      leading: CircleAvatar(
                        backgroundColor: avatarColor.withValues(alpha:0.12),
                        child: Text(e.category[0],
                            style: TextStyle(
                                fontWeight: FontWeight.bold, color: avatarColor)),
                      ),
                      title: Row(children: [
                        Expanded(
                          child: Text(e.description,
                              style: const TextStyle(fontWeight: FontWeight.w600)),
                        ),
                        if (isAuto) ...[
                          const SizedBox(width: 6),
                          _AutoBadge(isCogs: isCogs),
                        ],
                      ]),
                      subtitle: Text([
                        e.category,
                        df.format(e.date),
                        if (e.paymentType.isNotEmpty) e.paymentType,
                      ].join('  •  ')),
                      trailing: Row(mainAxisSize: MainAxisSize.min, children: [
                        Text(cf.format(e.amount),
                            style: TextStyle(
                                fontWeight: FontWeight.bold,
                                color: isCogs
                                    ? Colors.brown.shade600
                                    : AppTheme.payable)),
                        if (!isAuto)
                          IconButton(
                            icon: const Icon(Icons.delete_outline,
                                size: 18, color: Colors.red),
                            onPressed: () async {
                              final ok = await showDialog<bool>(
                                context: context,
                                builder: (_) => AlertDialog(
                                  title: const Text('Delete Expense?'),
                                  actions: [
                                    TextButton(
                                        onPressed: () =>
                                            Navigator.pop(context, false),
                                        child: const Text('Cancel')),
                                    TextButton(
                                        onPressed: () =>
                                            Navigator.pop(context, true),
                                        child: const Text('Delete',
                                            style:
                                                TextStyle(color: Colors.red))),
                                  ],
                                ),
                              );
                              if (ok == true) await svc.deleteExpense(e.id);
                            },
                          )
                        else
                          // Spacer to keep alignment consistent
                          const SizedBox(width: 40),
                      ]),
                    ),
                  );
                },
              ),
            ),
          ]);
        },
      ),
    );
  }
}

class _AutoBadge extends StatelessWidget {
  final bool isCogs;
  const _AutoBadge({required this.isCogs});

  @override
  Widget build(BuildContext context) {
    final color = isCogs ? Colors.brown.shade500 : AppTheme.primary;
    final label = isCogs ? 'COGS' : 'MFG';
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 5, vertical: 2),
      decoration: BoxDecoration(
        color: color.withValues(alpha:0.1),
        borderRadius: BorderRadius.circular(4),
        border: Border.all(color: color.withValues(alpha:0.4)),
      ),
      child: Text(label,
          style: TextStyle(fontSize: 9, fontWeight: FontWeight.bold, color: color)),
    );
  }
}

class _CategoryChip extends StatelessWidget {
  final String label, value;
  final Color color;
  const _CategoryChip(this.label, this.value, this.color);
  @override
  Widget build(BuildContext context) => Container(
    margin: const EdgeInsets.only(right: 8, top: 8, bottom: 4),
    padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
    decoration: BoxDecoration(
      color: color.withValues(alpha:0.1),
      borderRadius: BorderRadius.circular(20),
      border: Border.all(color: color.withValues(alpha:0.4)),
    ),
    child: Column(mainAxisSize: MainAxisSize.min, children: [
      Text(label, style: TextStyle(fontSize: 10, color: color)),
      Text(value,
          style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: color)),
    ]),
  );
}
