class ExpenseModel {
  final String id;
  final String category;
  final String description;
  final double amount;
  final String paymentType;
  final DateTime date;
  final String? notes;
  final String? partyName;
  // 'manual' (default/null) | 'manufacturing' | 'wages'
  final String? source;
  // production record ID (manufacturing) or worker ID (wages)
  final String? referenceId;

  ExpenseModel({
    required this.id,
    required this.category,
    required this.description,
    required this.amount,
    required this.paymentType,
    DateTime? date,
    this.notes,
    this.partyName,
    this.source,
    this.referenceId,
  }) : date = date ?? DateTime.now();

  bool get isAutoGenerated => source != null && source != 'manual';
  bool get isCogs => category == 'Raw Materials (COGS)';

  // Full category list (includes COGS — auto-generated only)
  static const List<String> categories = [
    'Raw Materials', 'Raw Materials (COGS)', 'Labor', 'Utilities',
    'Transport', 'Maintenance', 'Misc',
  ];

  // Categories available in the manual Add Expense form
  static const List<String> manualCategories = [
    'Raw Materials', 'Labor', 'Utilities', 'Transport', 'Maintenance', 'Misc',
  ];

  Map<String, dynamic> toMap() => {
    'id': id,
    'category': category,
    'description': description,
    'amount': amount,
    'paymentType': paymentType,
    'date': date.toIso8601String(),
    'notes': notes,
    'partyName': partyName,
    if (source != null) 'source': source,
    if (referenceId != null) 'referenceId': referenceId,
  };

  factory ExpenseModel.fromMap(Map<String, dynamic> m) => ExpenseModel(
    id: m['id'] ?? '',
    category: m['category'] ?? 'Misc',
    description: m['description'] ?? '',
    amount: (m['amount'] ?? 0).toDouble(),
    paymentType: m['paymentType'] ?? '',
    date: m['date'] != null ? DateTime.parse(m['date']) : DateTime.now(),
    notes: m['notes'],
    partyName: m['partyName'],
    source: m['source'],
    referenceId: m['referenceId'],
  );
}